project_id = "dsqhrenlenlsywallwzq"

[functions.create-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false

[functions.download-video]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.generate-scene-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false